name: CI

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: apk add --no-cache git nodejs bash curl

      - name: Install Bun
        run: |
          wget -qO- https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: $HOME/.bun/bin/bun install

      - name: Run lint
        run: $HOME/.bun/bin/bun run lint

      # - name: Run check
      #   run: $HOME/.bun/bin/bun run svelte-check

      - name: Run build
        run: $HOME/.bun/bin/bun run build
